wandb_version: 1

vocab_size:
  desc: null
  value: 10
n_a:
  desc: null
  value: 5
rnn_act_ftn:
  desc: null
  value: tanh
d_rnn:
  desc: null
  value: 128
d_model:
  desc: null
  value: 512
d_embed:
  desc: null
  value: 256
d_head:
  desc: null
  value: 64
d_inner:
  desc: null
  value: 2048
div_val:
  desc: null
  value: 4
pre_lnorm:
  desc: null
  value: true
n_layer:
  desc: null
  value: 2
n_head:
  desc: null
  value: 8
mem_len:
  desc: null
  value: 32
ext_len:
  desc: null
  value: 0
tgt_len:
  desc: null
  value: 32
same_length:
  desc: null
  value: false
attn_type:
  desc: null
  value: 1
clamp_len:
  desc: null
  value: 0
dropout:
  desc: null
  value: 0.1
dropatt:
  desc: null
  value: 0.0
untie_r:
  desc: null
  value: true
correction:
  desc: null
  value: false
init:
  desc: null
  value: normal
init_range:
  desc: null
  value: 0.01
proj_init_std:
  desc: null
  value: 0.01
init_std:
  desc: null
  value: 0.02
layer_norm_epsilon:
  desc: null
  value: 1.0e-05
ffn_act_ftn:
  desc: null
  value: nmda
alpha:
  desc: null
  value: 0.1
beta:
  desc: null
  value: 1
side_len:
  desc: null
  value: 11
run_dir:
  desc: null
  value: ./runs
proj_name:
  desc: null
  value: predictive coding
group_name:
  desc: null
  value: nmda_experiments
num_envs:
  desc: null
  value: 32
batch_size:
  desc: null
  value: 512
steps_per_epoch:
  desc: null
  value: 64
learning_rate:
  desc: null
  value: 0.0001
max_grad_norm:
  desc: null
  value: 0.25
training_epoch:
  desc: null
  value: 200
warmup_epoch:
  desc: null
  value: 0
log_image_interval:
  desc: null
  value: 10
seed:
  desc: null
  value: 0
gpu:
  desc: null
  value: 0
log_to_wandb:
  desc: null
  value: true
walk_length:
  desc: null
  value: 2048
_wandb:
  desc: null
  value:
    python_version: 3.8.19
    cli_version: 0.16.4
    framework: huggingface
    huggingface_version: 4.20.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711137507.0
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 16
      - 23
      4: 3.8.19
      5: 0.16.4
      6: 4.20.0
      8:
      - 3
      - 5
      13: windows-amd64
